src/MVC6ApiClientExample/Models/Album.cs
using Newtonsoft.Json;

namespace MVC6ApiClientExample.Models
{
    public class Album
    {
        [JsonProperty("_id")]
        public string Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("artist")]
        public string Artist { get; set; }
    }
}

src/MVC6ApiClientExample/Controllers/AlbumsController.cs
using System;
using Microsoft.AspNet.Mvc;
using MVC6ApiClientExample.Models;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Text;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MVC6ApiClientExample.Controllers
{
    public class AlbumsController : Controller
    {
        string _baseUrl = "http://localhost:8000/api/albums/";

        public AlbumsController()
        {

        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var requestUrl = _baseUrl;
            var httpClient = new HttpClient();

            List<Album> albums;

            using (var response = await httpClient.GetAsync(requestUrl))
            {
                if (!response.IsSuccessStatusCode)
                {
                    throw new Exception(String.Format("Server error (HTTP {0}: {1}).", response.StatusCode, response.Content));
                }

                var json = await response.Content.ReadAsStringAsync();
                albums = JsonConvert.DeserializeObject(json, typeof(List<Album>)) as List<Album>;
            }

            return View(albums);
        }

        public async Task<IActionResult> Detail(string id)
        {
            var requestUrl = _baseUrl + id;
            var httpClient = new HttpClient();

            Album album;

            using (var response = await httpClient.GetAsync(requestUrl))
            {
                if (!response.IsSuccessStatusCode)
                {
                    throw new Exception(String.Format("Server error (HTTP {0}: {1}).", response.StatusCode, response.Content));
                }

                var json = await response.Content.ReadAsStringAsync();
                album = JsonConvert.DeserializeObject(json, typeof(Album)) as Album;
            }

            return View(album);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var requestUrl = _baseUrl + id;
            var httpClient = new HttpClient();

            Album album;

            using (var response = await httpClient.GetAsync(requestUrl))
            {
                if (!response.IsSuccessStatusCode)
                {
                    throw new Exception(String.Format("Server error (HTTP {0}: {1}).", response.StatusCode, response.Content));
                }

                var json = await response.Content.ReadAsStringAsync();
                album = JsonConvert.DeserializeObject(json, typeof(Album)) as Album;
            }

            return View(album);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Album album)
        {
            var requestUrl = _baseUrl + album.Id;
            var httpClient = new HttpClient();

            using (var response = await httpClient.PutAsync(requestUrl, new StringContent(JsonConvert.SerializeObject(album), Encoding.UTF8, "application/json")))
            {
                if (!response.IsSuccessStatusCode)
                {
                    throw new Exception(String.Format("Server error (HTTP {0}: {1}).", response.StatusCode, response.Content));
                }
            }

            //Go back to the list
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string id)
        {
            var requestUrl = _baseUrl + id;
            var httpClient = new HttpClient();
            
            using (var response = await httpClient.DeleteAsync(requestUrl))
            {
                if (!response.IsSuccessStatusCode)
                {
                    throw new Exception(String.Format("Server error (HTTP {0}: {1}).", response.StatusCode, response.Content));
                }
            }

            //Refresh the list
            return RedirectToAction("Index");
        }
        
        public IActionResult Create()
        {
            var newAlbum = new Album();

            return View(newAlbum);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Album album)
        {
            var requestUrl = _baseUrl;
            var httpClient = new HttpClient();

            using (var response = await httpClient.PostAsync(requestUrl, new StringContent(JsonConvert.SerializeObject(album), Encoding.UTF8, "application/json")))
            {
                if (!response.IsSuccessStatusCode)
                {
                    throw new Exception(String.Format("Server error (HTTP {0}: {1}).", response.StatusCode, response.Content));
                }
            }

            //Go back to the list
            return RedirectToAction("Index");
        }

    }
}

src/MVC6ApiClientExample/Views/Albums/Create.cshtml
@model MVC6ApiClientExample.Models.Album

@{
    ViewBag.Title = "Add New Album";
}

<h1>@ViewBag.Title</h1>

<p>
    <a asp-controller="Albums" asp-action="Index" class="btn btn-primary">Back to List</a>
</p>

@using (Html.BeginForm())
{

    if (Model != null)
    {
        <fieldset>

            <label class="control-label">Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title"></span>

            <label class="control-label">Artist</label>
            <input asp-for="Artist" class="form-control" />
            <span asp-validation-for="Artist"></span>

            <div class="navigation">
                <div class="buttonholder">
                    <input type="submit" value="Save" class="btn btn-default btn-success" />
                </div>
            </div>
        </fieldset>
    }
}

src/MVC6ApiClientExample/Views/Albums/Detail.cshtml
@model MVC6ApiClientExample.Models.Album

@{
    ViewBag.Title = "Album Detail";
}

<h2>@ViewBag.Title</h2>

<p>
    <a asp-controller="Albums" asp-action="Index" class="btn btn-primary">Back to List</a>
</p>

<table>
    <tr>
        <th>Title</th>
        <th>Artist</th>
    </tr>
    <tr>
        <td>@Model.Title</td>
        <td>@Model.Artist</td>
    </tr>
</table>

<a asp-controller="Albums" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit this Album</a>

src/MVC6ApiClientExample/Views/Albums/Edit.cshtml
@model MVC6ApiClientExample.Models.Album

@{
    ViewBag.Title = "Edit Album";
}

<h1>@ViewBag.Title</h1>

<p>
    <a asp-controller="Albums" asp-action="Index" class="btn btn-primary">Back to List</a>
</p>

@using (Html.BeginForm())
{

    if (Model != null)
    {
        <fieldset>

            <label class="control-label">Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title"></span>

            <label class="control-label">Artist</label>
            <input asp-for="Artist" class="form-control" />
            <span asp-validation-for="Artist"></span>

            <div class="navigation">
                <div class="buttonholder">
                    <input type="submit" value="Save" class="btn btn-default btn-success" />
                </div>
            </div>
        </fieldset>
    }
}

src/MVC6ApiClientExample/Views/Albums/Index.cshtml
@model List<MVC6ApiClientExample.Models.Album>

@{ 
    ViewBag.Title = "Albums";
}

<h2>@ViewBag.Title</h2>

<!--//Before new tag helpers
//@Html.ActionLink("Add Album", "Create", "Albums", null, new { @class = "btn btn-primary" })
//Using new tag Helpers-->
<a asp-controller="Albums" asp-action="Create" class="btn btn-primary">Add Album</a>

<table>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th></th>
    </tr>
    @foreach(var album in Model)
    {
        <tr>
            <!--//Before new tag helpers
            //<td>@Html.ActionLink(album.Title, "Detail", new { id = album.Id })</td>
            //Using new tag helpers-->
            <td><a asp-controller="Albums" asp-action="Detail" asp-route-id="@album.Id">@album.Title</a></td>

            <td>@album.Artist</td>
            
            <!--//Before new tag helpers
            <td>@Html.ActionLink("Delete", "Delete", "Albums", new { id = album.Id }, new { @class = "btn btn-danger", onclick = "return confirm('Are you sure?')" })</td>
            //Using new tag helpers-->
            <td><a asp-controller="Albums" asp-action="Delete" asp-route-id="@album.Id" class="btn btn-danger" onclick = "return confirm('Are you sure?')">Delete</a></td>

        </tr>
    }
</table>

src/MVC6ApiClientExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Albums" asp-action="Index" class="navbar-brand">Simple REST API MVC 6 Example Client</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Albums" asp-action="Index">Albums</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>